import { useState } from "react";
import { Sparkles } from "lucide-react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import api, { toAIError } from "../api/client";
import type { ReferenceSheet, Workflow } from "../types";

/**
 * Generate the canonical image for a sheet, rather than uploading one.
 *
 * A place established once and referenced by every shot in its scene is what
 * keeps three shots of a hallway in one hallway; three paragraphs describing
 * the hallway do not. Two produced episodes were held together this way and
 * both had their plates generated by a script, because the bible could only
 * accept an upload.
 *
 * The seed is offered because a plate is a thing you re-make until it is
 * right, and re-making it with a different seed changes the place rather than
 * the picture of it.
 */
export default function ReferencePlateGenerator({
  projectId,
  sheet,
  workflows,
}: {
  projectId: string;
  sheet: ReferenceSheet;
  workflows: Workflow[];
}) {
  const [open, setOpen] = useState(false);
  const [prompt, setPrompt] = useState(sheet.canonical_description ?? "");
  const [workflowId, setWorkflowId] = useState("");
  const [seed, setSeed] = useState("");
  const qc = useQueryClient();

  const generate = useMutation({
    mutationFn: () =>
      api.references.generateImage(projectId, sheet.id, {
        prompt,
        negative_prompt: sheet.negative_tokens ?? "",
        workflow_id: workflowId || undefined,
        seed: seed.trim() === "" ? undefined : Number(seed),
      }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["references", projectId] });
    },
  });

  const seedValid =
    seed.trim() === "" ||
    (Number.isInteger(Number(seed)) && Number(seed) >= 0 && Number(seed) <= 2147483647);

  if (!open) {
    return (
      <button
        type="button"
        onClick={() => setOpen(true)}
        className="inline-flex items-center gap-1 text-xs text-indigo-400"
      >
        <Sparkles size={13} />
        Generate canonical image
      </button>
    );
  }

  return (
    <div className="space-y-2 rounded border border-zinc-700 p-2">
      <p className="text-xs font-medium text-zinc-300">Generate canonical image</p>
      <label className="block text-xs text-zinc-400">
        Prompt
        <textarea
          aria-label="Plate prompt"
          rows={3}
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          className="mt-1 w-full rounded border border-zinc-700 bg-zinc-900 px-2 py-1.5 text-xs text-zinc-100"
        />
      </label>
      <div className="flex gap-2">
        <label className="block flex-1 text-xs text-zinc-400">
          Workflow
          <select
            aria-label="Plate workflow"
            value={workflowId}
            onChange={(e) => setWorkflowId(e.target.value)}
            className="mt-1 w-full rounded border border-zinc-700 bg-zinc-900 px-2 py-1.5 text-xs text-zinc-100"
          >
            <option value="">Project default</option>
            {workflows.map((workflow) => (
              <option key={workflow.id} value={workflow.id}>
                {workflow.name}
              </option>
            ))}
          </select>
        </label>
        <label className="block w-28 text-xs text-zinc-400">
          Seed
          <input
            aria-label="Plate seed"
            value={seed}
            onChange={(e) => setSeed(e.target.value)}
            placeholder="random"
            className="mt-1 w-full rounded border border-zinc-700 bg-zinc-900 px-2 py-1.5 text-xs text-zinc-100"
          />
        </label>
      </div>
      <p className="text-[11px] text-zinc-400">
        The negative tokens on this sheet are sent with it. Nothing is replaced:
        a generated plate is added to the sheet beside whatever it already has.
      </p>
      <div className="flex gap-2">
        <button
          type="button"
          disabled={!prompt.trim() || !seedValid || generate.isPending}
          onClick={() => generate.mutate()}
          className="rounded bg-indigo-600 px-3 py-1 text-xs text-white disabled:opacity-50"
        >
          {generate.isPending ? "Generating…" : "Generate"}
        </button>
        <button
          type="button"
          onClick={() => setOpen(false)}
          className="rounded border border-zinc-700 px-2 py-1 text-xs text-zinc-300"
        >
          Cancel
        </button>
      </div>
      {generate.isError && (
        <p role="alert" className="text-xs text-red-300">
          {toAIError(generate.error).detail}
        </p>
      )}
    </div>
  );
}
