"""What a shot will actually be generated by, in words.

`generation_mode` is the only thing the cockpit shows, and it cannot answer
the question people keep asking. "video" covers both text-to-video and
reference-to-video, which are different models producing different results
from different inputs. Two shots reading "video" in the storyboard can be
routed to entirely different graphs and nothing on screen says so.

The route is the mode, the workflow that will run, and how many reference
images it will actually be sent - the three things together, derived rather
than typed in, so it cannot disagree with what generation does.
"""

import uuid

import pytest
from sqlalchemy.orm import Session

from app.models import Shot, Workflow
from app.services import job_payload, shot_route


def _workflow(db, name, mapping, purpose="image-to-video"):
    workflow = Workflow(
        id=str(uuid.uuid4()), name=name, purpose=purpose,
        source_json_path="", source_format="api", validation_status="valid",
        parameter_mapping=mapping, output_mapping=[],
    )
    db.add(workflow)
    db.commit()
    return workflow


def _shot(db, scene, **kwargs):
    shot = Shot(id=str(uuid.uuid4()), scene_id=scene.id, order=1, **kwargs)
    db.add(shot)
    db.commit()
    return shot


def test_a_still_says_so(db_session: Session, sample_project, sample_scene):
    workflow = _workflow(db_session, "Z-Image Turbo T2I", {
        job_payload.POSITIVE_PROMPT: {"nodeId": "6", "field": "text"},
    }, purpose="image")
    shot = _shot(db_session, sample_scene, generation_mode="image",
                 workflow_preset_id=workflow.id)

    route = shot_route.describe(db_session, sample_project.id, shot)

    assert route["label"] == "Text to image"
    assert route["workflow_name"] == "Z-Image Turbo T2I"
    assert route["reference_capacity"] == 0


def test_an_edit_route_is_named_by_the_references_it_takes(
    db_session: Session, sample_project, sample_scene,
):
    """One reference means editing a picture, not generating one from words."""
    workflow = _workflow(db_session, "Boogu Image Edit", {
        job_payload.POSITIVE_PROMPT: {"nodeId": "6", "field": "text"},
        job_payload.REFERENCE_IMAGE: {"nodeId": "4", "field": "image"},
    }, purpose="image")
    shot = _shot(db_session, sample_scene, generation_mode="image",
                 workflow_preset_id=workflow.id)

    route = shot_route.describe(db_session, sample_project.id, shot)

    assert route["label"] == "Reference to image"
    assert route["reference_capacity"] == 1


def test_video_without_references_is_text_to_video(
    db_session: Session, sample_project, sample_scene,
):
    workflow = _workflow(db_session, "H3 Video T2V", {
        job_payload.POSITIVE_PROMPT: {"nodeId": "6", "field": "text"},
    }, purpose="text-to-video")
    shot = _shot(db_session, sample_scene, generation_mode="video",
                 workflow_preset_id=workflow.id)

    route = shot_route.describe(db_session, sample_project.id, shot)

    assert route["label"] == "Text to video"


def test_video_with_references_is_reference_to_video(
    db_session: Session, sample_project, sample_scene,
):
    """The distinction the mode alone cannot make.

    Both of these read "video" on the storyboard today, and they are not the
    same thing: one composes a scene from a description, the other is told who
    is in it.
    """
    workflow = _workflow(db_session, "H3 Video R2V", {
        job_payload.POSITIVE_PROMPT: {"nodeId": "6", "field": "text"},
        job_payload.REFERENCE_IMAGE: {"nodeId": "137", "field": "image"},
        job_payload.reference_image_field(1): {
            "nodeId": "139", "field": "image", "optional": True,
        },
    })
    shot = _shot(db_session, sample_scene, generation_mode="video",
                 workflow_preset_id=workflow.id)

    route = shot_route.describe(db_session, sample_project.id, shot)

    assert route["label"] == "Reference to video"
    assert route["reference_capacity"] == 2
    assert route["reference_minimum"] == 1


def test_image_to_video_keeps_its_own_name(
    db_session: Session, sample_project, sample_scene,
):
    """A clip that animates a given frame is not the same as one told who is
    in it, even though both take a reference."""
    workflow = _workflow(db_session, "H3 Video I2V", {
        job_payload.POSITIVE_PROMPT: {"nodeId": "6", "field": "text"},
        job_payload.REFERENCE_IMAGE: {"nodeId": "114", "field": "image"},
    })
    shot = _shot(db_session, sample_scene, generation_mode="image-to-video",
                 workflow_preset_id=workflow.id)

    route = shot_route.describe(db_session, sample_project.id, shot)

    assert route["label"] == "Image to video"


def test_a_route_with_an_end_frame_says_so(
    db_session: Session, sample_project, sample_scene,
):
    workflow = _workflow(db_session, "H3 I2V + End Frame", {
        job_payload.POSITIVE_PROMPT: {"nodeId": "6", "field": "text"},
        job_payload.REFERENCE_IMAGE: {"nodeId": "114", "field": "image"},
        job_payload.END_FRAME_IMAGE: {"nodeId": "1", "field": "image"},
    })
    shot = _shot(db_session, sample_scene, generation_mode="image-to-video",
                 workflow_preset_id=workflow.id)

    route = shot_route.describe(db_session, sample_project.id, shot)

    assert route["accepts_end_frame"] is True


def test_a_shot_with_no_workflow_says_that_rather_than_guessing(
    db_session: Session, sample_project, sample_scene,
):
    """Naming a route nothing is assigned to would be the wrong answer."""
    shot = _shot(db_session, sample_scene, generation_mode="video")

    route = shot_route.describe(db_session, sample_project.id, shot)

    assert route["workflow_name"] == ""
    assert "No workflow" in route["detail"]


def test_a_hosted_provider_is_named_instead_of_a_workflow(
    db_session: Session, sample_project, sample_scene,
):
    """OpenAI Images runs no graph, so a workflow name would be a fiction."""
    shot = _shot(db_session, sample_scene, generation_mode="image",
                 image_provider_id="openai", image_model="gpt-image-1")

    route = shot_route.describe(db_session, sample_project.id, shot)

    assert route["provider_id"] == "openai"
    assert route["workflow_name"] == ""


@pytest.mark.parametrize("mode", ["image", "video", "image-to-video"])
def test_every_mode_produces_a_label(
    db_session: Session, sample_project, sample_scene, mode,
):
    shot = _shot(db_session, sample_scene, generation_mode=mode)
    route = shot_route.describe(db_session, sample_project.id, shot)
    assert route["label"]
