"""
Character Set Generator.

A character set answers "what does this person look like?" once, as a
*version* of canonical views - front, side, back, full body, an expression -
generated from one identity spec. Versions accumulate and exactly one is
approved as canonical; that approved version is the only thing downstream
generation is conditioned on.

Three rules hold throughout:

* **Approval is a pointer, never a deletion.** A newer approved version
  supersedes the old one. Every version keeps its images, so an approved take
  generated months ago can still be explained.
* **Views are real references.** Generated bytes are stored through
  :mod:`app.services.reference_bible` onto a sheet the set owns, so a canonical
  view reaches a provider through the same validated, ownership-checked path as
  a hand-uploaded plate. There is exactly one way an image can condition a job.
* **Identity has a digest.** ``canonical_digest`` folds the approved version's
  spec and image hashes into one value, which is what selective staleness
  compares against when the canonical identity moves.
"""

import hashlib
import json
import logging
from datetime import datetime, timezone
from typing import Any

from sqlalchemy.orm import Session

from app.models import (
    CharacterSet,
    CharacterSetVersion,
    CharacterSetView,
    ReferenceImage,
    ReferenceSheet,
)
from app.services import reference_bible

logger = logging.getLogger("cas.character_sets")


# ---------------------------------------------------------------------------
# Vocabulary
# ---------------------------------------------------------------------------

#: The canonical view slots a version may contain, in the order a character
#: sheet is conventionally read. Deliberately closed: each slot carries a
#: different instruction to the generator, and an unrecognised one would
#: silently produce an unlabelled image that nothing downstream could use.
VIEW_SLOTS: tuple[str, ...] = (
    "front",
    "three_quarter",
    "side",
    "back",
    "full_body",
    "expression",
    "pose",
)

#: What each slot asks the generator for. Appended to the identity spec when a
#: view's prompt is compiled, so the same spec yields consistent coverage.
SLOT_DIRECTIVES: dict[str, str] = {
    "front": (
        "front-facing character reference view, head-on, neutral expression, "
        "arms relaxed at the sides, even studio lighting, plain background"
    ),
    "three_quarter": (
        "three-quarter turn character reference view, body angled 45 degrees, "
        "neutral expression, even studio lighting, plain background"
    ),
    "side": (
        "full profile character reference view, exact side-on, neutral "
        "expression, even studio lighting, plain background"
    ),
    "back": (
        "rear character reference view, facing directly away, even studio "
        "lighting, plain background"
    ),
    "full_body": (
        "full-body character reference view, head to feet in frame, standing "
        "in a neutral A-pose, even studio lighting, plain background"
    ),
    "expression": (
        "expression sheet close-up of the same character, head and shoulders, "
        "even studio lighting, plain background"
    ),
    "pose": (
        "action pose reference of the same character, full body in frame, "
        "even studio lighting, plain background"
    ),
}

#: The default sheet a new version generates when the caller names no slots.
DEFAULT_SLOTS: tuple[str, ...] = ("front", "side", "back", "full_body")

STATUS_DRAFT = "Draft"
STATUS_GENERATING = "Generating"
STATUS_NEEDS_REVIEW = "NeedsReview"
STATUS_APPROVED = "Approved"
STATUS_SUPERSEDED = "Superseded"
STATUS_FAILED = "Failed"

VIEW_PENDING = "Pending"
VIEW_GENERATING = "Generating"
VIEW_READY = "Ready"
VIEW_FAILED = "Failed"

#: Set fields a client may write. Anything else - project, sheet, canonical
#: pointer, digests - is ours.
EDITABLE_SET_FIELDS: tuple[str, ...] = (
    "name",
    "character_id",
    "appearance",
    "proportions",
    "wardrobe",
    "palette",
    "identity_tokens",
    "negative_tokens",
    "notes",
)


class CharacterSetError(Exception):
    """A character set operation was refused, with a machine-readable reason."""

    def __init__(self, message: str, code: str, *, shot_ids: list[str] | None = None):
        super().__init__(message)
        self.code = code
        #: Populated when something still depends on what was being changed.
        self.shot_ids = shot_ids or []


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _digest(payload: Any) -> str:
    encoded = json.dumps(payload, sort_keys=True, ensure_ascii=False, default=str)
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Spec
# ---------------------------------------------------------------------------

def spec_snapshot(character_set: CharacterSet) -> dict[str, str]:
    """The identity text a version is generated from, as a plain mapping."""
    return {
        "name": character_set.name or "",
        "appearance": character_set.appearance or "",
        "proportions": character_set.proportions or "",
        "wardrobe": character_set.wardrobe or "",
        "palette": character_set.palette or "",
        "identity_tokens": character_set.identity_tokens or "",
        "negative_tokens": character_set.negative_tokens or "",
        # The picture is part of who the character is, so swapping it has to
        # move the digest exactly as rewriting the appearance does - otherwise
        # an approved sheet keeps reading as canonical for a different subject.
        "source_image_id": character_set.source_image_id or "",
    }


def spec_digest(character_set: CharacterSet) -> str:
    return _digest(spec_snapshot(character_set))


def identity_description(character_set: CharacterSet) -> str:
    """The spec as one sentence-per-facet block, for prompt compilation."""
    snapshot = spec_snapshot(character_set)
    parts = [snapshot["name"]]
    for field in ("appearance", "proportions", "wardrobe"):
        value = snapshot[field].strip()
        if value:
            parts.append(value)
    palette = snapshot["palette"].strip()
    if palette:
        parts.append("colour palette: " + palette)
    tokens = snapshot["identity_tokens"].strip()
    if tokens:
        parts.append(tokens)
    return ". ".join(part.rstrip(". ") for part in parts if part).strip()


def compile_view_prompt(character_set: CharacterSet, slot: str) -> str:
    """The positive prompt for one view of one character."""
    directive = SLOT_DIRECTIVES.get(slot, slot.replace("_", " ") + " reference view")
    identity = identity_description(character_set)
    return f"{directive}. {identity}" if identity else directive


# ---------------------------------------------------------------------------
# Sets
# ---------------------------------------------------------------------------

def create_set(
    db: Session,
    *,
    project_id: str,
    name: str,
    character_id: str | None = None,
    appearance: str = "",
    proportions: str = "",
    wardrobe: str = "",
    palette: str = "",
    identity_tokens: str = "",
    negative_tokens: str = "",
    notes: str = "",
) -> CharacterSet:
    """Create a character set and the reference sheet its views live on."""
    if not (name or "").strip():
        raise CharacterSetError(
            "A character set needs a name so it can be recognised in the "
            "storyboard.",
            "missing_name",
        )

    character_set = CharacterSet(
        project_id=project_id,
        character_id=character_id or None,
        name=name.strip(),
        appearance=appearance or "",
        proportions=proportions or "",
        wardrobe=wardrobe or "",
        palette=palette or "",
        identity_tokens=identity_tokens or "",
        negative_tokens=negative_tokens or "",
        notes=notes or "",
    )
    db.add(character_set)
    db.flush()

    sheet = reference_bible.create_sheet(
        db,
        project_id=project_id,
        kind="character",
        name=character_set.name,
        subject_ref_id=character_id or None,
        canonical_description=identity_description(character_set),
        identity_tokens=identity_tokens or "",
        negative_tokens=negative_tokens or "",
        notes="Generated character set views.",
    )
    character_set.reference_sheet_id = sheet.id
    db.commit()
    db.refresh(character_set)
    return character_set


def attach_source_image(
    db: Session,
    character_set: CharacterSet,
    *,
    data: bytes,
    content_type: str = "",
    original_filename: str = "",
) -> ReferenceImage:
    """Attach the picture this identity is derived from.

    Filed on the same sheet as the views but with role ``source``: the store
    is content-addressed and validated in one place, and the role is what
    keeps a photograph of the subject from being resolved as a canonical view
    and sent to a shot as one.

    Replacing it moves the identity spec, so a sheet approved from the old
    picture reads as out of date rather than staying canonical for somebody
    else's face.
    """
    sheet = backing_sheet(db, character_set)
    if sheet is None:
        raise CharacterSetError(
            "This character set has no reference sheet to store a source "
            "image on.",
            "sheet_missing",
        )
    image = reference_bible.store_image(
        db,
        sheet=sheet,
        data=data,
        original_filename=original_filename or "source.png",
        content_type=content_type,
        role="source",
        caption=f"{character_set.name} - source image",
        source="upload",
        source_detail={"character_set_id": character_set.id},
    )
    character_set.source_image_id = image.id
    db.commit()
    db.refresh(character_set)
    return image


def update_set(
    db: Session, character_set: CharacterSet, changes: dict[str, Any]
) -> CharacterSet:
    """Apply an edit to a set's identity spec.

    The approved version is left exactly where it is. Editing the spec does not
    retroactively change what was approved; it changes what the *next* version
    would be generated from, and the difference is what
    :func:`approved_version_is_current` reports.
    """
    if "name" in changes and changes["name"] is not None:
        if not str(changes["name"]).strip():
            raise CharacterSetError("A character set needs a name.", "missing_name")
        changes = {**changes, "name": str(changes["name"]).strip()}

    for field, value in changes.items():
        if field in EDITABLE_SET_FIELDS and value is not None:
            setattr(character_set, field, value)

    sheet = backing_sheet(db, character_set)
    if sheet is not None:
        reference_bible.update_sheet(
            db,
            sheet,
            {
                "name": character_set.name,
                "canonical_description": identity_description(character_set),
                "identity_tokens": character_set.identity_tokens or "",
                "negative_tokens": character_set.negative_tokens or "",
            },
        )
    db.commit()
    db.refresh(character_set)
    return character_set


def list_sets(db: Session, project_id: str) -> list[CharacterSet]:
    return (
        db.query(CharacterSet)
        .filter(CharacterSet.project_id == project_id)
        .order_by(CharacterSet.name)
        .all()
    )


def get_set(db: Session, project_id: str, set_id: str) -> CharacterSet | None:
    """Fetch one set, scoped to its project so a foreign id simply misses."""
    return (
        db.query(CharacterSet)
        .filter(
            CharacterSet.id == set_id,
            CharacterSet.project_id == project_id,
        )
        .first()
    )


def backing_sheet(db: Session, character_set: CharacterSet) -> ReferenceSheet | None:
    if not character_set.reference_sheet_id:
        return None
    return (
        db.query(ReferenceSheet)
        .filter(ReferenceSheet.id == character_set.reference_sheet_id)
        .first()
    )


def delete_set(db: Session, character_set: CharacterSet, *, force: bool = False) -> list[str]:
    """Delete a set, its versions and the sheet its views live on.

    Refused while a shot still binds to it, unless forced: dropping the
    canonical identity out from under a shot would silently un-condition its
    next generation.
    """
    dependents = shots_binding(db, [character_set.id])
    if dependents and not force:
        raise CharacterSetError(
            f"{len(dependents)} shot(s) still use this character set. Unbind "
            f"them first, or delete it with force to detach them.",
            "character_set_in_use",
            shot_ids=[shot.id for shot in dependents],
        )

    detached: list[str] = []
    for shot in dependents:
        shot.character_set_ids = [
            value
            for value in (shot.character_set_ids or [])
            if value != character_set.id
        ]
        detached.append(shot.id)

    sheet = backing_sheet(db, character_set)
    db.delete(character_set)
    db.flush()
    if sheet is not None:
        reference_bible.delete_sheet(db, sheet, force=True)
    db.commit()
    return detached


def shots_binding(db: Session, set_ids: list[str]):
    """Every shot that binds one of these character sets.

    ``character_set_ids`` is a JSON list, which SQLite cannot index into
    portably, so membership is tested in Python over the project's shots -
    projects here hold tens of shots, not millions.
    """
    from app.models import Scene, Shot

    if not set_ids:
        return []
    wanted = set(set_ids)
    project_ids = {
        row.project_id
        for row in db.query(CharacterSet).filter(CharacterSet.id.in_(set_ids)).all()
    }
    if not project_ids:
        return []
    shots = (
        db.query(Shot)
        .join(Scene, Shot.scene_id == Scene.id)
        .filter(Scene.project_id.in_(project_ids))
        .all()
    )
    return [s for s in shots if wanted & set(s.character_set_ids or [])]


# ---------------------------------------------------------------------------
# Versions
# ---------------------------------------------------------------------------

def normalise_slots(slots: list[str] | None) -> list[str]:
    """Validate requested slots, keeping the caller's order and dropping dupes."""
    requested = [str(slot or "").strip().lower() for slot in (slots or [])]
    requested = [slot for slot in requested if slot]
    if not requested:
        raise CharacterSetError(
            "A character set version needs at least one view. Choose from: "
            + ", ".join(VIEW_SLOTS)
            + ".",
            "no_slots",
        )
    seen: set[str] = set()
    ordered: list[str] = []
    for slot in requested:
        if slot not in VIEW_SLOTS:
            raise CharacterSetError(
                f"'{slot}' is not a character view. Use one of: "
                + ", ".join(VIEW_SLOTS)
                + ".",
                "invalid_slot",
            )
        if slot in seen:
            continue
        seen.add(slot)
        ordered.append(slot)
    return ordered


def create_version(
    db: Session,
    character_set: CharacterSet,
    *,
    slots: list[str] | None = None,
    provider_id: str = "",
    model: str = "",
    workflow_id: str | None = None,
    request_params: dict[str, Any] | None = None,
    seed: int | None = None,
    notes: str = "",
) -> CharacterSetVersion:
    """Open a new draft version with one pending view per requested slot."""
    ordered = normalise_slots(slots)

    highest = (
        db.query(CharacterSetVersion)
        .filter(CharacterSetVersion.character_set_id == character_set.id)
        .order_by(CharacterSetVersion.version.desc())
        .first()
    )
    next_version = (highest.version + 1) if highest else 1

    version = CharacterSetVersion(
        character_set_id=character_set.id,
        project_id=character_set.project_id,
        version=next_version,
        status=STATUS_DRAFT,
        spec_snapshot=spec_snapshot(character_set),
        spec_sha256=spec_digest(character_set),
        provider_id=provider_id or "",
        model=model or "",
        workflow_id=workflow_id,
        request_params=dict(request_params or {}),
        seed=seed,
        notes=notes or "",
    )
    db.add(version)
    db.flush()

    for order, slot in enumerate(ordered):
        db.add(CharacterSetView(
            version_id=version.id,
            character_set_id=character_set.id,
            project_id=character_set.project_id,
            slot=slot,
            label=slot.replace("_", " ").title(),
            order=order,
            view_prompt=compile_view_prompt(character_set, slot),
            status=VIEW_PENDING,
            provider_id=provider_id or "",
            model=model or "",
            workflow_id=workflow_id,
            seed=seed,
        ))

    db.flush()
    version.content_sha256 = version_content_digest(db, version)
    db.commit()
    db.refresh(version)
    return version


def list_versions(db: Session, character_set: CharacterSet) -> list[CharacterSetVersion]:
    return (
        db.query(CharacterSetVersion)
        .filter(CharacterSetVersion.character_set_id == character_set.id)
        .order_by(CharacterSetVersion.version)
        .all()
    )


def get_version(
    db: Session, character_set: CharacterSet, version_id: str
) -> CharacterSetVersion | None:
    return (
        db.query(CharacterSetVersion)
        .filter(
            CharacterSetVersion.id == version_id,
            CharacterSetVersion.character_set_id == character_set.id,
        )
        .first()
    )


def list_views(db: Session, version: CharacterSetVersion) -> list[CharacterSetView]:
    return (
        db.query(CharacterSetView)
        .filter(CharacterSetView.version_id == version.id)
        .order_by(CharacterSetView.order)
        .all()
    )


def version_content_digest(db: Session, version: CharacterSetVersion) -> str:
    """The spec plus every view's image hash, in view order.

    Image *hashes* rather than ids: regenerating a view to identical bytes is
    not a change, and should not invalidate work already approved against it.
    """
    views = list_views(db, version)
    return _digest({
        "spec": version.spec_sha256 or "",
        "views": [
            {
                "slot": view.slot,
                "sha256": view.image.sha256 if view.image is not None else "",
            }
            for view in views
        ],
    })


# ---------------------------------------------------------------------------
# View images
# ---------------------------------------------------------------------------

def attach_view_image(
    db: Session,
    view: CharacterSetView,
    *,
    data: bytes,
    content_type: str = "",
    original_filename: str = "",
    provenance: dict[str, Any] | None = None,
) -> CharacterSetView:
    """Store the bytes for one view and mark it ready.

    Validation, hashing and the stored path all come from the reference bible,
    so a generated view is indistinguishable downstream from an uploaded one -
    which is the point.
    """
    version = (
        db.query(CharacterSetVersion)
        .filter(CharacterSetVersion.id == view.version_id)
        .first()
    )
    if version is None:
        raise CharacterSetError("This view has no version.", "version_missing")
    character_set = (
        db.query(CharacterSet)
        .filter(CharacterSet.id == version.character_set_id)
        .first()
    )
    sheet = backing_sheet(db, character_set) if character_set else None
    if sheet is None:
        raise CharacterSetError(
            "This character set has no reference sheet to store views on.",
            "sheet_missing",
        )

    detail = dict(provenance or {})
    image = reference_bible.store_image(
        db,
        sheet=sheet,
        data=data,
        original_filename=original_filename or f"{view.slot}.png",
        content_type=content_type,
        role="canonical",
        caption=f"{character_set.name} - {view.label or view.slot}",
        source="character_set",
        source_detail={
            "character_set_id": character_set.id,
            "character_set_version": version.version,
            "view_slot": view.slot,
            **detail,
        },
    )

    view.reference_image_id = image.id
    view.status = VIEW_READY
    view.error_message = ""
    view.provenance = {**dict(view.provenance or {}), **detail}
    if "provider_id" in detail:
        view.provider_id = str(detail["provider_id"] or "")
    if "model" in detail:
        view.model = str(detail["model"] or "")
    if "seed" in detail and isinstance(detail["seed"], int):
        view.seed = detail["seed"]
    db.flush()

    version.content_sha256 = version_content_digest(db, version)
    if version.status == STATUS_DRAFT and all(
        v.reference_image_id for v in list_views(db, version)
    ):
        version.status = STATUS_NEEDS_REVIEW
    db.commit()
    db.refresh(view)
    return view


def fail_view(db: Session, view: CharacterSetView, message: str) -> CharacterSetView:
    """Record that one view could not be generated, with the reason."""
    view.status = VIEW_FAILED
    view.error_message = (message or "")[:1000]
    version = (
        db.query(CharacterSetVersion)
        .filter(CharacterSetVersion.id == view.version_id)
        .first()
    )
    if version is not None and version.status in (STATUS_DRAFT, STATUS_GENERATING):
        version.status = STATUS_FAILED
    db.commit()
    db.refresh(view)
    return view


# ---------------------------------------------------------------------------
# Approval
# ---------------------------------------------------------------------------

def approve_version(
    db: Session, version: CharacterSetVersion
) -> CharacterSetVersion:
    """Make this version the set's canonical identity.

    Every view must carry an image: a half-generated sheet approved as
    canonical would condition later shots on a subset of the identity without
    saying so. The previously approved version is superseded, not deleted.
    """
    views = list_views(db, version)
    missing = [view.slot for view in views if not view.reference_image_id]
    if missing:
        raise CharacterSetError(
            "Every view must have an image before this version can be "
            "approved as canonical. Still missing: " + ", ".join(missing) + ".",
            "views_incomplete",
        )

    character_set = (
        db.query(CharacterSet)
        .filter(CharacterSet.id == version.character_set_id)
        .first()
    )
    if character_set is None:
        raise CharacterSetError("This version has no character set.", "set_missing")

    for other in list_versions(db, character_set):
        if other.id != version.id and other.status == STATUS_APPROVED:
            other.status = STATUS_SUPERSEDED

    version.status = STATUS_APPROVED
    version.approved_at = _utcnow()
    version.content_sha256 = version_content_digest(db, version)
    character_set.approved_version_id = version.id
    db.commit()
    db.refresh(version)
    return version


def unapprove_version(
    db: Session, version: CharacterSetVersion
) -> CharacterSetVersion:
    """Withdraw canonical status, leaving the set with no canonical identity."""
    character_set = (
        db.query(CharacterSet)
        .filter(CharacterSet.id == version.character_set_id)
        .first()
    )
    if character_set is not None and character_set.approved_version_id == version.id:
        character_set.approved_version_id = None
    if version.status == STATUS_APPROVED:
        version.status = STATUS_NEEDS_REVIEW
    db.commit()
    db.refresh(version)
    return version


def approved_version(
    db: Session, character_set: CharacterSet
) -> CharacterSetVersion | None:
    if not character_set.approved_version_id:
        return None
    return (
        db.query(CharacterSetVersion)
        .filter(CharacterSetVersion.id == character_set.approved_version_id)
        .first()
    )


def approved_version_is_current(
    db: Session, character_set: CharacterSet
) -> bool:
    """Whether the canonical version was generated from today's spec.

    False means the identity text has been edited since the canonical views
    were made. That is surfaced, never auto-corrected: regenerating a character
    sheet is a decision with a cost, and only the user makes it.
    """
    version = approved_version(db, character_set)
    if version is None:
        return False
    return (version.spec_sha256 or "") == spec_digest(character_set)


# ---------------------------------------------------------------------------
# Resolution
# ---------------------------------------------------------------------------

def canonical_digest(db: Session, character_set: CharacterSet) -> str:
    """One value covering the canonical identity a generation would use.

    Empty when nothing is approved, which is itself meaningful: a shot bound to
    a set with no canonical version hashes differently from one bound to a set
    that has one.
    """
    version = approved_version(db, character_set)
    if version is None:
        return ""
    return version.content_sha256 or version_content_digest(db, version)


def resolve_canonical_images(
    db: Session, project_id: str, set_ids: list[str]
) -> list[ReferenceImage]:
    """The approved canonical view images for these sets, in a stable order.

    Sets are visited in the order asked and their views in slot order, so the
    identity references a job records are reproducible. A set from another
    project, an unknown id, or a set with nothing approved contributes nothing:
    the caller's preflight is what turns those into a visible blocker.
    """
    if not set_ids:
        return []

    found = {
        character_set.id: character_set
        for character_set in db.query(CharacterSet)
        .filter(CharacterSet.id.in_(set_ids))
        .all()
    }

    images: list[ReferenceImage] = []
    seen: set[str] = set()
    for set_id in set_ids:
        character_set = found.get(set_id)
        if character_set is None or character_set.project_id != project_id:
            continue
        version = approved_version(db, character_set)
        if version is None:
            continue
        for view in list_views(db, version):
            image = view.image
            if image is None or image.id in seen:
                continue
            seen.add(image.id)
            images.append(image)
    return images


def canonical_problems(
    db: Session, project_id: str, set_ids: list[str]
) -> list[str]:
    """Why the requested canonical identity cannot be used, in plain words.

    Returned as blockers rather than resolved silently: a shot that names a
    character set is asking to be conditioned on it, so a set with nothing
    approved must stop the run instead of producing an unconditioned render.
    """
    problems: list[str] = []
    if not set_ids:
        return problems

    found = {
        character_set.id: character_set
        for character_set in db.query(CharacterSet)
        .filter(CharacterSet.id.in_(set_ids))
        .all()
    }
    for set_id in set_ids:
        character_set = found.get(set_id)
        if character_set is None:
            problems.append(f"Character set {set_id} no longer exists.")
            continue
        if character_set.project_id != project_id:
            problems.append(
                f"Character set {set_id} belongs to another project and cannot "
                f"be used here."
            )
            continue
        version = approved_version(db, character_set)
        if version is None:
            problems.append(
                f"Character set '{character_set.name}' has no approved "
                f"canonical version. Generate and approve one first."
            )
            continue
        for view in list_views(db, version):
            if view.image is None:
                problems.append(
                    f"Character set '{character_set.name}' version "
                    f"{version.version} is missing its {view.slot} view image."
                )
    return problems
