"""What a shot will actually be generated by, in words.

`generation_mode` is the only thing the cockpit showed, and it cannot answer
the question people keep asking. "video" covers both text-to-video and
reference-to-video, which are different models producing different results
from different inputs; two shots reading "video" in the storyboard can be
routed to entirely different graphs with nothing on screen to say so.

A route is the mode, the workflow that will run, and how many reference images
it will be sent. All three are derived from the same records generation reads,
so the label cannot drift from what actually happens.
"""

from __future__ import annotations

from typing import Any

from sqlalchemy.orm import Session

from app.models import Project, Scene, Shot, Workflow
from app.services import job_payload, media_providers

#: Mode plus "does it take references" is what names a route. The mode alone
#: cannot separate text-to-video from reference-to-video, which is the pair
#: people actually confuse.
_LABELS = {
    ("image", False): "Text to image",
    ("image", True): "Reference to image",
    ("video", False): "Text to video",
    ("video", True): "Reference to video",
    ("image-to-video", False): "Image to video",
    ("image-to-video", True): "Image to video",
}


def _workflow_for(db: Session, project: Project | None, shot: Shot) -> Workflow | None:
    workflow_id = shot.workflow_preset_id or (
        (project.default_image_workflow_id if shot.generation_mode == "image"
         else project.default_video_workflow_id)
        if project is not None else None
    )
    if not workflow_id:
        return None
    return db.query(Workflow).filter(Workflow.id == workflow_id).first()


def describe(db: Session, project_id: str, shot: Shot) -> dict[str, Any]:
    """Name the route this shot will take, and what it will be given.

    Never guesses: a shot with no workflow assigned says so rather than being
    labelled with the route it would probably have taken.
    """
    project = db.query(Project).filter(Project.id == project_id).first()
    if project is None:
        scene = db.query(Scene).filter(Scene.id == shot.scene_id).first()
        project = (
            db.query(Project).filter(Project.id == scene.project_id).first()
            if scene else None
        )

    mode = (shot.generation_mode or "image").lower()
    provider_id = media_providers.resolve_provider_id(
        shot.image_provider_id, mode
    ) if shot.image_provider_id else media_providers.COMFYUI

    if provider_id != media_providers.COMFYUI:
        # A hosted image API runs no graph, so naming a workflow would be a
        # fiction. The provider and model are the whole route.
        return {
            "label": _LABELS[(mode, False)],
            "mode": mode,
            "provider_id": provider_id,
            "model": shot.image_model or "",
            "workflow_name": "",
            "reference_capacity": 0,
            "reference_minimum": 0,
            "accepts_end_frame": False,
            "detail": f"{provider_id} · {shot.image_model or 'default model'}",
        }

    workflow = _workflow_for(db, project, shot)
    mapping = (workflow.parameter_mapping or {}) if workflow else {}
    capacity = job_payload.reference_capacity(mapping)
    minimum = job_payload.required_reference_count(mapping)
    end_frame = job_payload.END_FRAME_IMAGE in mapping

    label = _LABELS[(mode, capacity > 0)]
    if workflow is None:
        detail = "No workflow assigned, so this shot cannot be generated yet."
    else:
        span = (
            "no reference images"
            if capacity == 0
            else f"{minimum} reference image" + ("" if minimum == 1 else "s")
            if minimum == capacity
            else f"{minimum} to {capacity} reference images"
        )
        detail = f"{workflow.name} · {span}"
        if end_frame:
            detail += " · can be given an end frame"

    return {
        "label": label,
        "mode": mode,
        "provider_id": provider_id,
        "model": shot.image_model or "",
        "workflow_name": workflow.name if workflow else "",
        "reference_capacity": capacity,
        "reference_minimum": minimum,
        "accepts_end_frame": end_frame,
        "detail": detail,
    }
